### ISSUE TITLE
練習

### ISSUE THREAD

**Issue by tsukky1337** [hitobb/test#1]
こんばんわ(^^)
早速issueをあげてみます！
上手くいくかなー？

**Comment by hitobb** [comment]
オッケーです、届いていました。

では、次のミッション。
Tsukky1337さん側からクローズしてみてくださいｗ

**Comment by tsukky1337** [comment]
わーい(^^)
ではクローズしてみます！

**Comment by hitobb** [comment]
追加ミッション。
再オープンしてみてくださいな。

**Comment by tsukky1337** [comment]
ぱっかーん(*´ω｀*)

**Comment by hitobb** [comment]
オーナー権限で強制的に閉じてみる。
さて、再オープンできるかな?

**Comment by tsukky1337** [comment]
出来なくなりした(°_°)

**Comment by hitobb** [comment]
どうしてこういう作りになっているのでしょうか？

答え合わせは24時間後。
いろいろ考えてみてくださいな。

**Comment by tsukky1337** [comment]
まず思い浮かんだ答えです。

issue…議論すべき問題。
という事は、GitHubのissueはオーナーの資産に対する議題の提起なので、最終的な議論の決着はオーナーが決める。
故に一度決着のついた議論に追加で何か議題をあげる為には、新たにissueをあげる必要がある。という事でしょうか？

もっとざっくり表現してしまうと、
1件=1様とするため。

**Comment by hitobb** [comment]
OK、正解です！

これでissueの使い方は完璧ですねｗ

**Comment by tsukky1337** [comment]
わーい(*´ω｀*)
夜分遅くまでありがとうございます！！

それではおやすみなさい♩
