### ISSUE TITLE
mission for bitzeny

### ISSUE THREAD

**Issue by niufy** [hitobb/test#2]
こんにちは。
はじめてのissueです。
よろしくお願いします。

**Comment by hitobb** [comment]
おつかれさまです～
対応、遅くなってすいません～

以下のオペレーション、やってみてくださいな！

（１）このissueをniufyさん側からクローズする
（２）クローズした後に何か書き込む
（３）このissueを再オープンする

よろしくお願いいたします！

**Comment by niufy** [comment]
いえいえ、こちらこそ遅くなりすみません。
いつも対応ありがとうございます。
それでは、（２）、（３）続けていきます！

**Comment by niufy** [comment]
（３）いきます！

**Comment by hitobb** [comment]
確認しました。
それでは、
（４）今度は私がクローズします
（５）このissueを再オープンしてみてください
（６）どうしてこのような結果になったのか、コメントで残してみてください。
よろしくお願いします！

**Comment by niufy** [comment]
早速の対応ありがとうございます。

次なるミッションについてですが、このissueの再オープンはできないようです。
おそらく、（1）・（3）から、私のアカウントはこのissueの提案者として、次のことが可能なのだと思います。
・issueのオープン
・issueのクローズ（自分がオープンしたもののみ）
しかし、（4）・（5）から、その権限はこのリポジトリの管理者である「Owner」を超えるものではなく、「Owner」がクローズしたものを再オープンすることはできないものと考えます。

**Comment by hitobb** [comment]
大正解です！

この権限差があるので、オーナは的を得ていないIssueが連続してオープンされた場合などに、
強制的にクローズすることが可能となります。

逆に言えば、間違っていればオーナーが強制終了してくれるので、
報告を上げることに関して躊躇する必要はないとも言えます。

なんとなく使い方がイメージ頂ければ幸いです。

**Comment by niufy** [comment]
hitobbさん、分かりやすく説明していただき、ありがとうございます。
issueに対する「よくわからない感」がだいぶ払しょくされました。
